<a href="https://colab.research.google.com/github/jolly-thomas/cuddly-lamp/blob/main/Supervised%20Learning/Random_Forests.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [9]:
df=load_iris()
data=pd.DataFrame(df.data,columns=df.feature_names)
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [13]:
target=df.target
target=pd.DataFrame(target,columns=['target'])
target.shape

(150, 1)

In [14]:
x_train,x_test,y_train,y_test=train_test_split(data,target,test_size=0.2)

In [15]:
rc=RandomForestClassifier(n_estimators=180,criterion='gini',max_depth=3,oob_score=True,random_state=42,n_jobs=-1)
rc.fit(x_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier(max_depth=3, n_estimators=180, n_jobs=-1, oob_score=True,
                       random_state=42)

In [16]:
rc.predict(x_test)

array([2, 1, 2, 0, 2, 2, 0, 2, 2, 1, 1, 0, 0, 1, 1, 1, 0, 2, 1, 0, 1, 0,
       0, 2, 0, 1, 2, 2, 0, 2])

In [17]:
rc.score(x_test,y_test)

0.9666666666666667

In [18]:
rc.feature_importances_

array([0.09579931, 0.01517791, 0.49754894, 0.39147384])

In [19]:
rc.decision_path(x_test)

(<30x1540 sparse matrix of type '<class 'numpy.int64'>'
 	with 17522 stored elements in Compressed Sparse Row format>,
 array([   0,    9,   18,   25,   34,   41,   50,   59,   68,   77,   84,
          93,  102,  109,  118,  127,  134,  145,  152,  159,  168,  175,
         182,  189,  196,  205,  216,  223,  232,  241,  248,  255,  264,
         271,  282,  291,  300,  309,  318,  325,  334,  341,  348,  359,
         368,  377,  386,  391,  400,  411,  420,  429,  436,  445,  452,
         463,  472,  485,  494,  503,  512,  521,  534,  543,  552,  559,
         566,  575,  582,  591,  602,  617,  624,  633,  642,  651,  660,
         669,  676,  685,  696,  703,  710,  719,  728,  735,  744,  751,
         758,  765,  772,  781,  790,  801,  812,  819,  826,  835,  846,
         853,  862,  869,  880,  887,  896,  905,  914,  925,  936,  943,
         950,  957,  964,  975,  984,  991, 1000, 1011, 1024, 1033, 1042,
        1051, 1058, 1067, 1074, 1081, 1088, 1095, 1104, 1111, 1118,

In [22]:
print(classification_report(y_test,rc.predict(x_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.89      1.00      0.94         8
           2       1.00      0.92      0.96        12

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

